/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;
import Modelo.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import javax.swing.Action;
import javax.swing.JOptionPane;
/**
 *
 * @author vily0
 */
public class JInternalFrameCompras extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameProductos
     */
    public JInternalFrameCompras() {
        initComponents();
        jTextIID_Compras.setEnabled(false);
        
    }
    public void limpiarCampos() {
    jTextIID_Compras.setText("");
    jTextFecha_Compras.setText("");

}
    public void obtenerDatos() {
    List<Compras> compras = new DAOCompras().ObtenerDatos();
    DefaultTableModel modelo = new DefaultTableModel();
    String[] columnas = {"ID_Compras","Fecha_Compras"};
    modelo.setColumnIdentifiers(columnas);
    
    for (Compras com : compras) { 
        String[] renglon = {
            Integer.toString(com.getID_compras()),
            com.getFecha_Compras().toString()
        };
        modelo.addRow(renglon);
    }
    jTableCompras.setModel(modelo); 
}
    public void actualizarProducto() {
    int ID = Integer.parseInt(this.jTextIID_Compras.getText());
    Date fc = Date.valueOf(this.jTextFecha_Compras.getText());


    DAOCompras dao = new DAOCompras();
    int res = dao.Actualizar(ID, fc);
    if (res == 1) {
        JOptionPane.showMessageDialog(rootPane, "Compra Actualizada!");
    } else {
        JOptionPane.showMessageDialog(rootPane, "¡Ocurrió un ERROR!");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCompras = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextIID_Compras = new javax.swing.JTextField();
        jTextFecha_Compras = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBAgregarCO = new javax.swing.JButton();
        jBEditarCO = new javax.swing.JButton();
        jBactualizarCO = new javax.swing.JButton();
        CO = new javax.swing.JButton();
        jBBuscarCO = new javax.swing.JButton();
        jTextBuscarCO = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(168, 240, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Compras Registradas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jTableCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jTableCompras);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(168, 240, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Registrar / Actualizar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ID_Compra");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Fecha_Compra");

        jTextIID_Compras.setBorder(new javax.swing.border.MatteBorder(null));

        jTextFecha_Compras.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/farmacia (4) (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextIID_Compras)
                            .addComponent(jTextFecha_Compras)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextIID_Compras, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFecha_Compras, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(168, 240, 255));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jBAgregarCO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBAgregarCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carrito-de-compras (1).png"))); // NOI18N
        jBAgregarCO.setText("Agregar");
        jBAgregarCO.setBorder(new javax.swing.border.MatteBorder(null));
        jBAgregarCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarCOActionPerformed(evt);
            }
        });

        jBEditarCO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBEditarCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar (2).png"))); // NOI18N
        jBEditarCO.setText("Editar");
        jBEditarCO.setBorder(new javax.swing.border.MatteBorder(null));
        jBEditarCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarCOActionPerformed(evt);
            }
        });

        jBactualizarCO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBactualizarCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reciclar (1).png"))); // NOI18N
        jBactualizarCO.setText("Actualizar");
        jBactualizarCO.setBorder(new javax.swing.border.MatteBorder(null));
        jBactualizarCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBactualizarCOActionPerformed(evt);
            }
        });

        CO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar (1).png"))); // NOI18N
        CO.setText("Borrar");
        CO.setBorder(new javax.swing.border.MatteBorder(null));
        CO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COActionPerformed(evt);
            }
        });

        jBBuscarCO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBBuscarCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa (1).png"))); // NOI18N
        jBBuscarCO.setText("Buscar");
        jBBuscarCO.setBorder(new javax.swing.border.MatteBorder(null));
        jBBuscarCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarCOActionPerformed(evt);
            }
        });

        jTextBuscarCO.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jBAgregarCO, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jBEditarCO, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jBactualizarCO, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextBuscarCO, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBBuscarCO, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)))
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBAgregarCO)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEditarCO)
                    .addComponent(jBactualizarCO))
                .addGap(18, 18, 18)
                .addComponent(CO)
                .addGap(18, 18, 18)
                .addComponent(jBBuscarCO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextBuscarCO, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo De Vacaciones En Enfermera, Enfermero, Tratamiento Médico, Hospital Imagen de Fondo Para Descarga Gratuita - Pngtreee.jpeg"))); // NOI18N
        jLabel9.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 42, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAgregarCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarCOActionPerformed

String fc = jTextFecha_Compras.getText();

if (fc.contentEquals("")) {
    JOptionPane.showMessageDialog(rootPane, "El campo de ser rellenado");
}else{
    try {
    Date fch = Date.valueOf(fc);
    Compras pro = new DAOCompras().Insertar(fch);
    JOptionPane.showMessageDialog(rootPane, "Compra Agregada");
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(rootPane, "No se agregó la compra");
}

limpiarCampos();
}
    }//GEN-LAST:event_jBAgregarCOActionPerformed

    private void jBEditarCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarCOActionPerformed
        int fila = this.jTableCompras.getSelectedRow(); // Se obtiene #fila seleccionada
if (fila == -1) {
    JOptionPane.showMessageDialog(rootPane, "Seleccione un registro de la tabla");
} else { // Se toma cada campo de la tabla del registro seleccionado
    try {
        int ID = Integer.parseInt((String) this.jTableCompras.getValueAt(fila, 0).toString());
        Date fc = Date.valueOf((String) this.jTableCompras.getValueAt(fila, 1).toString());

        // Se ubican en las cajas de textos los datos capturados de la tabla
        jTextIID_Compras.setText("" + ID);
        jTextFecha_Compras.setText(String.valueOf(fc));
    } catch (NumberFormatException e) {
        e.printStackTrace();
    }
}
    }//GEN-LAST:event_jBEditarCOActionPerformed

    private void jBactualizarCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBactualizarCOActionPerformed
        actualizarProducto();
        this.obtenerDatos();
        this.limpiarCampos();
    }//GEN-LAST:event_jBactualizarCOActionPerformed

    private void COActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COActionPerformed
        int fila = this.jTableCompras.getSelectedRow();
if (fila == -1) {
    JOptionPane.showMessageDialog(rootPane, "Seleccione un registro de la tabla");
} else {
    int ID = Integer.parseInt((String) this.jTableCompras.getValueAt(fila, 0).toString());
    DAOCompras dao = new DAOCompras();
    dao.Eliminar(ID);
    obtenerDatos();
}
    }//GEN-LAST:event_COActionPerformed

    private void jBBuscarCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarCOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBBuscarCOActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CO;
    private javax.swing.JButton jBAgregarCO;
    private javax.swing.JButton jBBuscarCO;
    private javax.swing.JButton jBEditarCO;
    private javax.swing.JButton jBactualizarCO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCompras;
    private javax.swing.JTextField jTextBuscarCO;
    private javax.swing.JTextField jTextFecha_Compras;
    private javax.swing.JTextField jTextIID_Compras;
    // End of variables declaration//GEN-END:variables
}
