/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;
import Modelo.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author vily0
 */
public class JInternalFrameProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameProductos
     */
    public JInternalFrameProductos() {
        initComponents();
        jTextIdProducto.setEnabled(false);
        
    }
    public void limpiarCampos() {
    jTextIdProducto.setText("");
    jTextNombres.setText("");
    jTextCategoria.setText("");
    jTextDescripcion.setText("");
    jTextCantidad.setText("");
    jTextFechaVen.setText("");
}
    public void obtenerDatos() {
    List<Producto> producto = new DAOProducto().ObtenerDatos();
    DefaultTableModel modelo = new DefaultTableModel();
    String[] columnas = {"id_autor", "Nombres", "Apellidos", "Email", "Cédula", "FechaNac"};
    modelo.setColumnIdentifiers(columnas);
    
    for (Producto pro : producto) { 
        String[] renglon = {
            Integer.toString(pro.getId_productos()),
            pro.getNombre(),
            pro.getCategoria(),
            pro.getDescripcion(),
            Integer.toString(pro.getCantidad()),
            Double.toString(pro.getPrec_unit()),
            pro.getFechaVen().toString()
        };
        modelo.addRow(renglon);
    }
    jTableProductos.setModel(modelo); 
}
    public void actualizarProducto() {
    int id = Integer.parseInt(this.jTextIdProducto.getText());
    String nom = this.jTextNombres.getText();
    String cate = this.jTextCategoria.getText();
    String des = this.jTextDescripcion.getText();
    int can = Integer.parseInt(this.jTextCantidad.getText());
    Date fec = Date.valueOf(this.jTextFechaVen.getText());
    double prec = Double.parseDouble(this.jTextPrecio.getText());

    DAOProducto dao = new DAOProducto();
    int res = dao.Actualizar(id, nom, cate, des, can, fec, prec);
    if (res == 1) {
        JOptionPane.showMessageDialog(rootPane, "Autor Actualizado!");
    } else {
        JOptionPane.showMessageDialog(rootPane, "¡Ocurrió un ERROR!");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextIdProducto = new javax.swing.JTextField();
        jTextNombres = new javax.swing.JTextField();
        jTextCategoria = new javax.swing.JTextField();
        jTextDescripcion = new javax.swing.JTextField();
        jTextCantidad = new javax.swing.JTextField();
        jTextFechaVen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextPrecio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBAgregarP = new javax.swing.JButton();
        jBEditarP = new javax.swing.JButton();
        jBactualizarP = new javax.swing.JButton();
        jBBorrarP = new javax.swing.JButton();
        jBBuscarP = new javax.swing.JButton();
        jTextBuscarP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(168, 240, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Productos Registrados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(jTableProductos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(168, 240, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Registrar / Actualizar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Categoria");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Descripcion");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Cantidad");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Fecha_Ven");

        jTextIdProducto.setBorder(new javax.swing.border.MatteBorder(null));

        jTextNombres.setBorder(new javax.swing.border.MatteBorder(null));
        jTextNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombresActionPerformed(evt);
            }
        });

        jTextCategoria.setBorder(new javax.swing.border.MatteBorder(null));

        jTextDescripcion.setBorder(new javax.swing.border.MatteBorder(null));

        jTextCantidad.setBorder(new javax.swing.border.MatteBorder(null));

        jTextFechaVen.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Precio");

        jTextPrecio.setBorder(new javax.swing.border.MatteBorder(null));
        jTextPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPrecioActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/farmacia (4) (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jTextCantidad)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(12, 12, 12)
                                .addComponent(jTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextFechaVen))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFechaVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        jPanel2.setBackground(new java.awt.Color(168, 240, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Transacciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jBAgregarP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBAgregarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carrito-de-compras (1).png"))); // NOI18N
        jBAgregarP.setText("Agregar");
        jBAgregarP.setBorder(new javax.swing.border.MatteBorder(null));
        jBAgregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarPActionPerformed(evt);
            }
        });

        jBEditarP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBEditarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar (2).png"))); // NOI18N
        jBEditarP.setText("Editar");
        jBEditarP.setBorder(new javax.swing.border.MatteBorder(null));
        jBEditarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarPActionPerformed(evt);
            }
        });

        jBactualizarP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBactualizarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reciclar (1).png"))); // NOI18N
        jBactualizarP.setText("Actualizar");
        jBactualizarP.setBorder(new javax.swing.border.MatteBorder(null));
        jBactualizarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBactualizarPActionPerformed(evt);
            }
        });

        jBBorrarP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBBorrarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar (1).png"))); // NOI18N
        jBBorrarP.setText("Borrar");
        jBBorrarP.setBorder(new javax.swing.border.MatteBorder(null));
        jBBorrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarPActionPerformed(evt);
            }
        });

        jBBuscarP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBBuscarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa (1).png"))); // NOI18N
        jBBuscarP.setText("Buscar");
        jBBuscarP.setBorder(new javax.swing.border.MatteBorder(null));
        jBBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarPActionPerformed(evt);
            }
        });

        jTextBuscarP.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBAgregarP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBEditarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jBactualizarP, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBBuscarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBBorrarP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextBuscarP))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAgregarP)
                .addGap(1, 1, 1)
                .addComponent(jLabel10)
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEditarP)
                    .addComponent(jBactualizarP))
                .addGap(18, 18, 18)
                .addComponent(jBBorrarP)
                .addGap(18, 18, 18)
                .addComponent(jBBuscarP)
                .addGap(18, 18, 18)
                .addComponent(jTextBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo De Vacaciones En Enfermera, Enfermero, Tratamiento Médico, Hospital Imagen de Fondo Para Descarga Gratuita - Pngtreee.jpeg"))); // NOI18N
        jLabel9.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAgregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarPActionPerformed
        String nomb = jTextNombres.getText();
String cate = jTextCategoria.getText();
String des = jTextDescripcion.getText();
int can = Integer.parseInt(jTextCantidad.getText());
double prec = Double.parseDouble(jTextPrecio.getText());
String fecV = jTextFechaVen.getText();

if (nomb.contentEquals("") || cate.contentEquals("") || 
    des.contentEquals("") || can <= 0 ||
    prec <= 0||
    fecV.contentEquals("")) {
    JOptionPane.showMessageDialog(rootPane, "Todos los campos son obligatorios");
}else{
    try {
    Date fech = Date.valueOf(fecV);
    Producto pro = new DAOProducto().Insertar(nomb, cate, des, can, fech, prec);
    JOptionPane.showMessageDialog(rootPane, "Registro agregado");
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(rootPane, "No se agregó el registro");
}

limpiarCampos();
}
    }//GEN-LAST:event_jBAgregarPActionPerformed

    private void jBEditarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarPActionPerformed
        int fila = this.jTableProductos.getSelectedRow(); // Se obtiene #fila seleccionada
if (fila == -1) {
    JOptionPane.showMessageDialog(rootPane, "Seleccione un registro de la tabla");
} else { // Se toma cada campo de la tabla del registro seleccionado
    try {
        int id = Integer.parseInt((String) this.jTableProductos.getValueAt(fila, 0).toString());
        String nom = (String) this.jTableProductos.getValueAt(fila, 1);
        String cate = (String) this.jTableProductos.getValueAt(fila, 2);
        String des = (String) this.jTableProductos.getValueAt(fila, 3);
        int can = Integer.parseInt((String) this.jTableProductos.getValueAt(fila, 4));
        double prec = Double.parseDouble((String) this.jTableProductos.getValueAt(fila, 5));
        Date fec = Date.valueOf((String) this.jTableProductos.getValueAt(fila, 6).toString());

        // Se ubican en las cajas de textos los datos capturados de la tabla
        jTextIdProducto.setText("" + id);
        jTextNombres.setText(nom);
        jTextCategoria.setText(cate);
        jTextDescripcion.setText(des);
        jTextCantidad.setText(String.valueOf(can));
        jTextPrecio.setText(String.valueOf(prec));
        jTextFechaVen.setText(String.valueOf(fec));
    } catch (NumberFormatException e) {
        e.printStackTrace();
    }
}
    }//GEN-LAST:event_jBEditarPActionPerformed

    private void jBactualizarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBactualizarPActionPerformed
        actualizarProducto();
        this.obtenerDatos();
        this.limpiarCampos();
    }//GEN-LAST:event_jBactualizarPActionPerformed

    private void jBBorrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarPActionPerformed
        int fila = this.jTableProductos.getSelectedRow();
if (fila == -1) {
    JOptionPane.showMessageDialog(rootPane, "Seleccione un registro de la tabla");
} else {
    int id = Integer.parseInt((String) this.jTableProductos.getValueAt(fila, 0).toString());
    DAOProducto dao = new DAOProducto();
    dao.Eliminar(id);
    obtenerDatos();
}
    }//GEN-LAST:event_jBBorrarPActionPerformed

    private void jBBuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBBuscarPActionPerformed

    private void jTextPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPrecioActionPerformed

    private void jTextNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregarP;
    private javax.swing.JButton jBBorrarP;
    private javax.swing.JButton jBBuscarP;
    private javax.swing.JButton jBEditarP;
    private javax.swing.JButton jBactualizarP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField jTextBuscarP;
    private javax.swing.JTextField jTextCantidad;
    private javax.swing.JTextField jTextCategoria;
    private javax.swing.JTextField jTextDescripcion;
    private javax.swing.JTextField jTextFechaVen;
    private javax.swing.JTextField jTextIdProducto;
    private javax.swing.JTextField jTextNombres;
    private javax.swing.JTextField jTextPrecio;
    // End of variables declaration//GEN-END:variables
}
