/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;
import Modelo.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author kristing y Yaleska
 */
public class JInternalFrameCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameProductos
     */
    public JInternalFrameCliente() {
        initComponents();
        jTextIdClientes.setEnabled(false);
        
    }
    public void limpiarCampos() {
    jTextIdClientes.setText("");
    jTextNombresC.setText("");
    jTextApellidoC.setText("");
    jTextEmailC.setText("");
    jTextCedulaC.setText("");
    jTextTelefonoC.setText("");
}
    public void obtenerDatos() {
    List<Clientes> clientes = new DAOClientes().ObtenerDatos();
    DefaultTableModel modelo = new DefaultTableModel();
    String[] columnas = {"id_clientes", "NombreC", "ApellidoC", "EmailC", "CédulaC", "TelefonoC"};
    modelo.setColumnIdentifiers(columnas);
    
    for (Clientes cli : clientes) { 
        String[] renglon = {
            Integer.toString(cli.getId_Clientes()),
            cli.getNombreC(),
            cli.getApellidoC(),
            cli.getEmailC(),
            Integer.toString(cli.getCedulaC()),
            Double.toString(cli.getTelefonoC()),
           
        };
        modelo.addRow(renglon);
    }
    jTableClientes.setModel(modelo); 
}
    public void actualizarClientes() {
    int id = Integer.parseInt(this.jTextIdClientes.getText());
    String nom = this.jTextNombresC.getText();
    String apell = this.jTextApellidoC.getText();
    String ema = this.jTextEmailC.getText();
    int ced = Integer.parseInt(this.jTextCedulaC.getText());
    int tel = Integer.parseInt(this.jTextTelefonoC.getText());
    

    DAOClientes dao = new DAOClientes();
    int res = dao.Actualizar(id, nom, apell, ema, ced, tel);
    if (res == 1) {
        JOptionPane.showMessageDialog(rootPane, "Autor Actualizado!");
    } else {
        JOptionPane.showMessageDialog(rootPane, "¡Ocurrió un ERROR!");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextIdClientes = new javax.swing.JTextField();
        jTextNombresC = new javax.swing.JTextField();
        jTextApellidoC = new javax.swing.JTextField();
        jTextEmailC = new javax.swing.JTextField();
        jTextCedulaC = new javax.swing.JTextField();
        jTextTelefonoC = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBAgregarP = new javax.swing.JButton();
        jBEditarP = new javax.swing.JButton();
        jBactualizarP = new javax.swing.JButton();
        jBBorrarP = new javax.swing.JButton();
        jBBuscarP = new javax.swing.JButton();
        jTextBuscarP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(168, 240, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Registros de Clientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(jTableClientes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(168, 240, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Registrar / Actualizar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Apellido");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Cedula");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Telefono");

        jTextNombresC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombresCActionPerformed(evt);
            }
        });

        jTextTelefonoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelefonoCActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/farmacia (4) (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jTextCedulaC, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextTelefonoC))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextEmailC, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextApellidoC, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNombresC, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextIdClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextIdClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextNombresC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextApellidoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextEmailC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextCedulaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextTelefonoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(168, 240, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Transacciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jBAgregarP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBAgregarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carrito-de-compras (1).png"))); // NOI18N
        jBAgregarP.setText("Agregar");
        jBAgregarP.setBorder(new javax.swing.border.MatteBorder(null));
        jBAgregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarPActionPerformed(evt);
            }
        });

        jBEditarP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBEditarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar (2).png"))); // NOI18N
        jBEditarP.setText("Editar");
        jBEditarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarPActionPerformed(evt);
            }
        });

        jBactualizarP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBactualizarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reciclar (1).png"))); // NOI18N
        jBactualizarP.setText("Actualizar");
        jBactualizarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBactualizarPActionPerformed(evt);
            }
        });

        jBBorrarP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBBorrarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar (1).png"))); // NOI18N
        jBBorrarP.setText("Borrar");
        jBBorrarP.setBorder(new javax.swing.border.MatteBorder(null));
        jBBorrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarPActionPerformed(evt);
            }
        });

        jBBuscarP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBBuscarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa (1).png"))); // NOI18N
        jBBuscarP.setText("Buscar");
        jBBuscarP.setBorder(new javax.swing.border.MatteBorder(null));
        jBBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarPActionPerformed(evt);
            }
        });

        jTextBuscarP.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBAgregarP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBEditarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jBactualizarP))
                    .addComponent(jBBuscarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBBorrarP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextBuscarP))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBAgregarP)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEditarP)
                    .addComponent(jBactualizarP))
                .addGap(18, 18, 18)
                .addComponent(jBBorrarP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBBuscarP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo De Vacaciones En Enfermera, Enfermero, Tratamiento Médico, Hospital Imagen de Fondo Para Descarga Gratuita - Pngtreee.jpeg"))); // NOI18N
        jLabel9.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNombresCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombresCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombresCActionPerformed

    private void jBAgregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarPActionPerformed
        String nomb = jTextNombresC.getText();
String apell = jTextApellidoC.getText();
String ema = jTextEmailC.getText();
int ced = Integer.parseInt(jTextCedulaC.getText());
int tel = Integer.parseInt(jTextTelefonoC.getText());

if (nomb.contentEquals("") || apell.contentEquals("") || 
    ema.contentEquals("") || ced <= 0 ||
    tel <= 0 ) {
    JOptionPane.showMessageDialog(rootPane, "Todos los campos son obligatorios");
    
}else{
    try {
        
    Producto cli = new DAOClientes().Insertar(nomb, apell, ema , ced, tel);
    JOptionPane.showMessageDialog(rootPane, "Registro agregado");
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(rootPane, "No se agregó el registro");
}

limpiarCampos();
}
    }//GEN-LAST:event_jBAgregarPActionPerformed

    private void jBEditarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarPActionPerformed
        int fila = this.jTableClientes.getSelectedRow(); // Se obtiene #fila seleccionada
if (fila == -1) {
    JOptionPane.showMessageDialog(rootPane, "Seleccione un registro de la tabla");
} else { // Se toma cada campo de la tabla del registro seleccionado
    try {
        int id = Integer.parseInt((String) this.jTableClientes.getValueAt(fila, 0).toString());
        String nom = (String) this.jTableClientes.getValueAt(fila, 1);
        String apell = (String) this.jTableClientes.getValueAt(fila, 2);
        String ema = (String) this.jTableClientes.getValueAt(fila, 3);
        int ced = Integer.parseInt((String) this.jTableClientes.getValueAt(fila, 4));
        int tel = Integer.parseInt((String) this.jTableClientes.getValueAt(fila, 5));
        
        // Se ubican en las cajas de textos los datos capturados de la tabla
        jTextIdClientes.setText("" + id);
        jTextNombresC.setText(nom);
        jTextApellidoC.setText(apell);
        jTextEmailC.setText(ema);
        jTextCedulaC.setText(String.valueOf(ced));
        jTextTelefonoC.setText(String.valueOf(tel));
    } catch (NumberFormatException e) {
        e.printStackTrace();
    }
}
    }//GEN-LAST:event_jBEditarPActionPerformed

    private void jBactualizarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBactualizarPActionPerformed
        actualizarClientes();
        this.obtenerDatos();
        this.limpiarCampos();
    }//GEN-LAST:event_jBactualizarPActionPerformed

    private void jBBorrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarPActionPerformed
        int fila = this.jTableClientes.getSelectedRow();
if (fila == -1) {
    JOptionPane.showMessageDialog(rootPane, "Seleccione un registro de la tabla");
} else {
    int id = Integer.parseInt((String) this.jTableClientes.getValueAt(fila, 0).toString());
    DAOProducto dao = new DAOProducto();
    dao.Eliminar(id);
    obtenerDatos();
}
    }//GEN-LAST:event_jBBorrarPActionPerformed

    private void jBBuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBBuscarPActionPerformed

    private void jTextTelefonoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelefonoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelefonoCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregarP;
    private javax.swing.JButton jBBorrarP;
    private javax.swing.JButton jBBuscarP;
    private javax.swing.JButton jBEditarP;
    private javax.swing.JButton jBactualizarP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField jTextApellidoC;
    private javax.swing.JTextField jTextBuscarP;
    private javax.swing.JTextField jTextCedulaC;
    private javax.swing.JTextField jTextEmailC;
    private javax.swing.JTextField jTextIdClientes;
    private javax.swing.JTextField jTextNombresC;
    private javax.swing.JTextField jTextTelefonoC;
    // End of variables declaration//GEN-END:variables
}
